importcsv/urls.py
from django.conf.urls import url

from . import views

app_name = 'importcsv'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^uploadcsv/$', views.uploadcsv, name='uploadcsv'),
    url(r'^importcategories/$', views.importcategories, name='importcategories'),
    url(r'^api/$', views.api, name='api'),
]

workolist/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('importcsv.urls')),
    url(r'^admin/', admin.site.urls),
]

importcsv/models.py
from django.db import models

class Channel(models.Model):
    """
    Class responsible for creating the data model of objects reallocated to the Channels
    """
    #Fields models/object
    name = models.CharField('Name Channel:', max_length=20, unique=True, blank=False)
    description = models.CharField('Description:',max_length=50, null=True, blank=True)
    category_channel = models.ManyToManyField(
        'Category',
    )
    #return a string reference to name the object
    def __str__(self):
        return self.name
    #Metadata the model
    class Meta:
        ordering = ['name']
        get_latest_by = ['id']

class Category(models.Model):
    """
    Class responsible for creating the data model of the objects that are reallocated to Categories
    """
    #Fields models/object
    name = models.CharField('Name:', max_length=20, blank=False)
    description = models.CharField('Description:', max_length=50, null=True, blank=True)
    sub_category = models.ManyToManyField(
        'SubCategory',
    )
    #return a string reference to name the object
    def __str__(self):
        return self.name
    #Metadata the model
    class Meta:
        ordering = ['name']
        get_latest_by = ['id']

class SubCategory(models.Model):
    """
    Class responsible for creating the data model of objects that are reallocated to Sub-categories
    """
    #Fields models/object
    name = models.CharField('Name SubCategory:', max_length=20, default=" ", blank=False)
    description = models.CharField('Description:',max_length=50, null=True, blank=True)

    #return a string reference to name the object
    def __str__(self):
        return self.name
    #Metadata the model
    class Meta:
        ordering = ['name']
        get_latest_by = ['id']

importcsv/views.py
#Libraries
from django.shortcuts import render
from django.core.files.uploadedfile import UploadedFile
from .models import Category, Channel, SubCategory
from django.http import HttpResponse
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core import serializers
import csv

#vision responsible for redecorating the initial template.
def index(request):
    return render(request, 'importcsv/index.html')

#vision responsible for rendering all the page for manipulation of the template
def api(request):
    allchannel = Channel.objects.all()
    onlycs = Channel.objects.get(pk=1).category_channel.all()[:1]
    context = {
        'allchannel': allchannel,
        'onlycs':onlycs,
    }
    return render(request, 'importcsv/api.html', context)

#vision responsible to do upload the file .csv which includes all categorys
def uploadcsv(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage(location='importcsv/media')
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'importcsv/uploadcsv.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'importcsv/uploadcsv.html')

#vision responsible for updating categories and subcategories of a channel that already exists in the database
#or creating a new channel with its categories and sub categories if it does not
def importcategories(request):
    if request.method == 'POST':
        channelalt = request.POST['channel_name']
        channel_filter = Channel.objects.filter(name=channelalt)
        uploaded = UploadedFile(open('importcsv/media/category.csv', 'r'), 'category.csv')
        if len(channel_filter) > 0:
            #update channel
            pk_channel = channel_filter[0].pk
            Channel.objects.get(pk=pk_channel).category_channel.all().delete()

            for [line] in csv.reader(uploaded.file):
                data = line.split('/')
                category_name = data[0]
                subcategory_name = data[1]
                Channel.objects.get(pk=pk_channel).category_channel.create(name=category_name, description='New Category')
                category_filter = Category.objects.filter(name=category_name).latest('id')
                pk_category = category_filter.pk
                Category.objects.get(pk=pk_category).sub_category.create(name=subcategory_name, description='New Sub-Category')

            return render(request, 'importcsv/uploadcsv.html', {
                'category_filter': category_filter
            })
        else:
            #create new channel
            newchannel = Channel(name=channelalt, description='New Channel')
            newchannel.save()
            for [line] in csv.reader(uploaded.file):

                data = line.split('/')
                category_name = data[0]
                subcategory_name = data[1]
                newchannel.category_channel.create(name=category_name, description='New Category')
                category_filter = Category.objects.filter(name=category_name).latest('id')
                pk_category = category_filter.pk
                Category.objects.get(pk=pk_category).sub_category.create(name=subcategory_name, description='New Sub-Category')

            return render(request, 'importcsv/uploadcsv.html', {
                'category_filter': category_filter
            })

importcsv/templates/importcsv/api.html
{% extends 'importcsv/base.html' %}

{% block content %}
        <div>
          <h3>|-- Channel /</h3>
          {% if allchannel %}
              <ul>
              {% for channel in allchannel %}
                  <li><b>{{ channel.name }} </b></li>
              {% endfor %}
              {% else %}
                  <p>No channel are available.</p>
          {% endif %}

          <h3>|--  Channel / Category /</h3>
          {% if allchannel %}
              <ul>
              {% for channel in allchannel %}
                  <b>|--  {{ channel.name }} </b> -- {{ channel.description }}
                  {% for name in channel.category_channel.all %}
                        {% for sub in name.sub_category.all%}
                          <p style="padding-left: 1.5em;">|-- {{ name }} / {{ sub }} /</p>
                        {% endfor %}
                  {% endfor %}
              {% endfor %}
              </ul>
          {% else %}
              <p>No channel/category are available.</p>
          {% endif %}

          <h3>|-- Only Category / SubCategory /</h3>
          <ul>
          {% if allchannel %}
              {% for name in onlycs %}
                    |-- {{ name }} /
                    {% for subname in name.sub_category.all  %}
                      <p style="padding-left: 1.5em;">|-- {{ subname }} /</p>
                    {% endfor %}
              {% endfor %}
          {% endif %}
          </ul>


        </div>
{% endblock content %}

importcsv/templates/importcsv/base.html
{% load static %}

<!DOCTYPE html PUBLIC>
<htmt lang="en">
<head>
  <link rel="stylesheet" href="{% static 'importcsv/css/bootstrap.min.css' %}"/>

    <title>{% block title %}Work Olist{% endblock %}</title>
</head>

<body>
    <div class="btn-group" id="sidebar">
        {% block sidebar %}
        </br>
        <a class="btn btn-primary" href="{% url 'importcsv:index' %}" role="button">home <span class="glyphicon glyphicon-home"></a>
        <a class="btn btn-primary" href="{% url 'importcsv:uploadcsv' %}" role="button">Import .CSV<span class="glyphicon glyphicon-download-alt"></span></a>
        <a class="btn btn-primary" href="{% url 'importcsv:api' %}" role="button">View Channel/Category <span class="glyphicon glyphicon-tags"></a>
        <a class="btn btn-primary" href="/admin/" role="button">Admin <span class="glyphicon glyphicon-cog"></a>

        {% endblock %}
    </div>

    <div class="well" id="content" style="margin-top: 20px;">
        {% block content %}


        {% endblock %}
    </div>
</body>
</html>

importcsv/templates/importcsv/index.html
{% extends 'importcsv/base.html' %}

{% block content %}
        <div>
          <h4>|-- Import or view Channel and Category</h4>
        </div>
{% endblock content %}

importcsv/templates/importcsv/uploadcsv.html
{% extends 'importcsv/base.html' %}

{% block content %}
        <div>
          <h4><b>|-- Import a file .CSV</b></h4>
          </br>
          <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
              <input class="btn btn-default" type="file" name="myfile">
              <button class="btn btn-default"  type="submit">Upload</button>
          </form>
          {% if uploaded_file_url %}
            <p>File upload Sucessefull!! <span class="glyphicon glyphicon-refresh"></p>
          {% endif %}
          <h4><b>|-- Update or create a new channel</b></h4>
          </br>
        </div>
        <div class="row">
            <div class="col-md-10">
                <div class="input-group col-md-3">
                    <form action="{% url 'importcsv:importcategories' %}" method="post">
                      {% csrf_token %}
                      <input type="text" name="channel_name" id="channel_name" class="form-control" placeholder="Enter the channel name">
                      <input class="btn btn-default" type="submit" value="Update/Create">
                    </form>
                </div>
                {% if category_filter %}
                  <p>Sucessefull!! <span class="glyphicon glyphicon-refresh"></p>
                {% endif %}
            </div>
        </div>
{% endblock content %}